server:
  port: 8766

spring:
  application:
    name: sleuth-zipkin
  #zipkin服务端地址
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 指定需采样的请求的百分比，默认是0.1（即10%），这里方便查看设为100%（实际环境不要这样设置）
      probability: 0.2

userService:
  url: http://localhost:8768/user/

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
