spring:
  application:
    name: hystrix

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.springcloud.hystrix.feign.UserFeignClient: debug

userService:
  url: http://user-service/user/