spring:
  application:
    name: ribbon

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

userService:
  url: http://user-service/user/

ribbon: # 通过属性更改负载均衡规则，默认是RoundRobinRule
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #随机选择一个server
  #com.netflix.loadbalancer.BestAvailableRule:选择一个最小的并发请求的server
  #com.netflix.loadbalancer.AvailabilityFilteringRule:过滤掉那些因为一直连接失败的被标记为circuit tripped的后端server
  #com.netflix.loadbalancer.RoundRobinRule:roundRobin方式轮询选择server
  #com.netflix.loadbalancer.WeightedResponseTimeRule:根据响应时间分配一个weight，weight越小越容易选中
  #com.netflix.loadbalancer.RetryRule:根据负载均衡策略重试
  #com.netflix.loadbalancer.ZoneAvoidanceRule:复合判断server所在区域的性能和server的可用性进行选择